name: saturn-moonlet

services:
  prometheus-exporter:
    build:
      context: .
      dockerfile: docker/prometheus-exporter/Dockerfile
    restart: unless-stopped
    pull_policy: build
    env_file: docker/prometheus-exporter/.env
    ports:
      - 127.0.0.1:9000:9000/tcp
    volumes:
      - ./docker/prometheus-exporter/conf:/conf:ro

  prometheus:
    image: prom/prometheus:v2.45.1
    restart: unless-stopped
    command:
      # Store 30 days of data.
      - --storage.tsdb.retention.time=30d
      # Below are the command line arguments taken from the upstream Dockerfile.
      # See https://github.com/prometheus/prometheus/blob/1ac5131f698ebc60f13fe2727f89b115a41f6558/Dockerfile
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    ports:
      - 127.0.0.1:9090:9090/tcp
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana-oss:10.0.1
    restart: unless-stopped
    env_file: docker/grafana/production/.env
    profiles:
      - production
    ports:
      - 443:443/tcp
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./docker/grafana/ssl:/etc/grafana/ssl:ro
      - ./docker/grafana/production/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana-data:/var/lib/grafana

  grafana-local:
    image: grafana/grafana-oss:10.0.1
    restart: unless-stopped
    env_file: docker/grafana/local/.env
    profiles:
      - local
    ports:
      - 127.0.0.1:3000:3000/tcp
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./docker/grafana/local/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana-data:/var/lib/grafana

volumes:
  prometheus-data:
  grafana-data:
