on: pull_request

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.11.3
          cache: pip
          cache-dependency-path: |
            dev-requirements.txt

      - name: Install Python requirements
        run: |
          pip install --upgrade pip
          pip install --no-deps -r dev-requirements.txt

      # This file is required for Docker Compose validation.
      - name: Create empty .env file
        run: touch docker/prometheus-exporter/.env

      - name: Run checks
        run: make check
